### ISSUE TITLE
Cannot convert type System.Windows.Forms.TabControl

### ISSUE THREAD

**Issue by cpuguru** [turtlecoin/turtle-wallet-winforms#29]
Getting the following error when I try to build Release/Any CPU -

Error	CS0266	Cannot implicitly convert type 'System.Windows.Forms.TabControl' to 'TurtleWallet.NoBorderTabControl'. An explicit conversion exists (are you missing a cast?)	TurtleWallet	C:\Users\dw\Documents\GitHub\desktop-xamarin\wallet.Designer.cs	71	Active

**Comment by ZedPea** [comment]
This this PR https://github.com/turtlecoin/desktop-xamarin/pull/28

**Comment by cpuguru** [comment]
Did you mean you wanted me to clone https://github.com/hensleyrob/desktop-xamarin and try to build that?

**Comment by ZedPea** [comment]
Yep, it fixed an error compiling in release so i assume that is your issue

**Comment by cpuguru** [comment]
It compiled without any errors.
